name: Trigger on pull_request (plan) and push (apply) events with fmt/validate checks and TFLint.

on:
  push:
    branches: [main]

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  tf:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      actions: read        # Required to identify workflow run.
      checks: write        # Required to add status summary.
      contents: read       # Required to checkout repository.
      pull-requests: write # Required to add PR comment.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup TF
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Init TF
        id: tf
        if: ${{ github.event_name == 'pull_request' }}
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: infra
          command: init
          arg-lock: false
          arg-backend-config: "backends/prod.tfbackend"
          format: true
          validate: true

      - name: Provision TF
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: infra
          command: ${{ github.event_name == 'push' && 'apply' || 'plan' }}
          arg-lock: ${{ github.event_name == 'push' }}
          arg-backend-config: "backends/prod.tfbackend"

      - name: Get Static Web App API Key
        id: get_api_key
        run: |
          API_KEY=$(terraform output -raw static_web_app_api_key)
          echo "API_KEY_MASKED::add-mask::$API_KEY" # Mask the value in logs
          echo "STATIC_WEB_APP_API_KEY=$API_KEY" >> $GITHUB_ENV # Store as env var for subsequent steps
        working-directory: "infra" # Adjust to your Terraform infra path

      - name: Deploy Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.STATIC_WEB_APP_API_KEY }}
          action: "upload"
          app_location: "static" # Your app's source code path
          api_location: ""  # Your API's source code path
          output_location: "" # Your app's build output path
        env:
          # Ensure the environment variable is available to this step if needed
          STATIC_WEB_APP_API_TOKEN: ${{ env.STATIC_WEB_APP_API_KEY }}
